### ISSUE TITLE
_rocketcore.dll build with MinGW 4.8.1 and python bindings

### ISSUE THREAD

**Issue by perrelle** [libRocket/libRocket#243]
When trying to build librocket with MinGW gcc 4.8.1 with Python bindings, the build of _rocketcore.dll fails when linking with error :

    CMakeFiles/_rocketcore.dir/objects.a(ElementDocumentWrapper.cpp.obj):ElementDocumentWrapper.cpp:(.text+0xd12): undefined reference to `_imp___ZN6Rocket4Core6Python9Utilities10PrintErrorEb'
    CMakeFiles/_rocketcore.dir/objects.a(ElementDocumentWrapper.cpp.obj):ElementDocumentWrapper.cpp:(.text+0xd59): undefined reference to `_imp___ZN6Rocket4Core6Python9Utilities10PrintErrorEb'

Before that, there was warnings of interests when building Core/Python/Utilities.cpp.obj regarding the use of the dllimport attribute:

    [ 91%] Building CXX object CMakeFiles/_rocketcore.dir/.../libRocket/Source/Core/Python/Utilities.cpp.obj

    .../libRocket/Source/Core/Python/Utilities.cpp:74:6: warning: 'static void Rocket::Core::Python::Utilities::PrintError(bool)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
     void Utilities::PrintError(bool clear_error)
