### ISSUE TITLE
Python bindings not compiling on OS X

### ISSUE THREAD

**Issue by underdoeg** [libRocket/libRocket#46]
Hi

the python bindings won't compile on OS X 10.6, boost 1.47. I got the following erros:
Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/bits/localefwd.h:58:34: error: macro "isspace" passed 2 arguments, but takes just 1
/Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/bits/localefwd.h:70:34: error: macro "isupper" passed 2 arguments, but takes just 1
/Developer/SDKs/MacOSX10.6.sdk/usr/include/c++/4.2.1/bits/localefwd.h:74:34: error: macro "islower" passed 2 arguments, but takes just 1
...

However after changing the import order in precompiled.h to 

```
// Python header.
#include <Rocket/Core/Python/Python.h>

// Rocket core and controls.
#include <Rocket/Core.h>
#include <Rocket/Controls.h>
```

instead of 

```
// Rocket core and controls.
#include <Rocket/Core.h>
#include <Rocket/Controls.h>

#include <Rocket/Core/Python/Python.h>
```

everything compiled fine
